CREATE TABLE countries
  (
    country_id   CHAR( 2 ) PRIMARY KEY  ,
    country_name VARCHAR2( 40 ) NOT NULL
  );

CREATE TABLE warehouses
  (
    warehouse_id NUMBER 
                 GENERATED BY DEFAULT AS IDENTITY
                 PRIMARY KEY,
    warehouse_name VARCHAR( 255 ) ,
    country_id     CHAR( 2 )      , -- fk
    CONSTRAINT fk_warehouses_countries
      FOREIGN KEY( country_id )
      REFERENCES countries( country_id ) 
      ON DELETE CASCADE
  );

CREATE TABLE product_categories
  (
    category_id NUMBER 
                GENERATED BY DEFAULT AS IDENTITY
                PRIMARY KEY,
    category_name VARCHAR2( 255 ) NOT NULL
  );

CREATE TABLE products
  (
    product_id NUMBER 
               GENERATED BY DEFAULT AS IDENTITY
               PRIMARY KEY,
    product_name  VARCHAR2( 255 ) NOT NULL,
    description   VARCHAR2( 2000 )        ,
    cost          NUMBER( 9, 2 )          ,
    price         NUMBER( 9, 2 )          ,
    category_id   NUMBER NOT NULL         , -- fk
    CONSTRAINT fk_products_categories 
      FOREIGN KEY( category_id )
      REFERENCES product_categories( category_id ) 
      ON DELETE CASCADE
  );

CREATE TABLE customers
  (
    customer_id NUMBER 
                GENERATED BY DEFAULT AS IDENTITY
                PRIMARY KEY,
    fist_name    VARCHAR2( 255 ) NOT NULL,
    last_name    VARCHAR2( 255 ) NOT NULL,
    address      VARCHAR2( 255 ) NOT NULL,
    email        VARCHAR2( 255 ) NOT NULL,
    country_id   CHAR(2)                 , -- fk
    CONSTRAINT fk_customers_countries 
      FOREIGN KEY( country_id )
      REFERENCES countries( country_id ) 
      ON DELETE CASCADE
  );

CREATE TABLE orders
  (
    order_id NUMBER 
             GENERATED BY DEFAULT AS IDENTITY
             PRIMARY KEY,
    customer_id NUMBER( 6, 0 ) NOT NULL, -- fk
    status      VARCHAR( 20 ) NOT NULL ,
    order_date  DATE NOT NULL          ,
    product_id NUMBER( 12, 0 ) NOT NULL, -- fk
    quantity   NUMBER( 8, 2 ) NOT NULL ,
    CONSTRAINT fk_orders_customers 
      FOREIGN KEY( customer_id )
      REFERENCES customers( customer_id )
      ON DELETE CASCADE,
    CONSTRAINT fk_orders_products 
      FOREIGN KEY( product_id )
      REFERENCES products( product_id )
      ON DELETE CASCADE
  );

CREATE TABLE inventories
  (
    product_id   NUMBER( 12, 0 )        , -- fk
    warehouse_id NUMBER( 12, 0 )        , -- fk
    quantity     NUMBER( 8, 0 ) NOT NULL,
    CONSTRAINT pk_inventories 
      PRIMARY KEY( product_id, warehouse_id ),
    CONSTRAINT fk_inventories_products 
      FOREIGN KEY( product_id )
      REFERENCES products( product_id ) 
      ON DELETE CASCADE,
    CONSTRAINT fk_inventories_warehouses 
      FOREIGN KEY( warehouse_id )
      REFERENCES warehouses( warehouse_id ) 
      ON DELETE CASCADE
  );